services:
  - type: web
    name: telegram-stories-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    autoDeploy: true